<a href="https://colab.research.google.com/github/LittleBopeep2020/Python_Class/blob/main/Project1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [8]:
df = pd.read_json('https://data.cityofnewyork.us/resource/csps-2ne9.json')

In [9]:
df.head()

,school_dbn,school_name,school_type,school_level,regents_exam,year,demographic_category,demographic_variable,total_tested,mean_score,number_scoring_below_65,percent_scoring_below_65,number_scoring_65_or_above,percent_scoring_65_or_above,number_scoring_80_or_above,percent_scoring_80_or_above,number_scoring_cr,percent_scoring_cr
0,01M034,P.S. 034 Franklin D. Roosevelt,General Academic,K-8,Common Core Algebra,2017,All Students,All Students,4,s,s,s,s,s,s,s,na,na
1,01M034,P.S. 034 Franklin D. Roosevelt,General Academic,K-8,Living Environment,2015,All Students,All Students,16,77.9,1,6.3,15,93.8,7,43.8,na,na
2,01M034,P.S. 034 Franklin D. Roosevelt,General Academic,K-8,Living Environment,2016,All Students,All Students,9,74.0,1,11.1,8,88.9,2,22.2,na,na
3,01M140,P.S. 140 Nathan Straus,General Academic,K-8,Common Core Algebra,2016,All Students,All Students,3,s,s,s,s,s,s,s,na,na
4,01M140,P.S. 140 Nathan Straus,General Academic,K-8,Common Core Algebra,2017,All Students,All Students,2,s,s,s,s,s,s,s,na,na

In [10]:
df.tail()

,school_dbn,school_name,school_type,school_level,regents_exam,year,demographic_category,demographic_variable,total_tested,mean_score,number_scoring_below_65,percent_scoring_below_65,number_scoring_65_or_above,percent_scoring_65_or_above,number_scoring_80_or_above,percent_scoring_80_or_above,number_scoring_cr,percent_scoring_cr
995,02M408,Professional Performing Arts High School,General Academic,Secondary School,Common Core Algebra,2015,All Students,All Students,113,67.9,29,25.7,84,74.3,8,7.1,51,45.1
996,02M408,Professional Performing Arts High School,General Academic,Secondary School,Common Core Algebra,2016,All Students,All Students,121,75.3,13,10.7,108,89.3,44,36.4,94,77.7
997,02M408,Professional Performing Arts High School,General Academic,Secondary School,Common Core Algebra,2017,All Students,All Students,96,80.8,3,3.1,93,96.9,68,70.8,89,92.7
998,02M408,Professional Performing Arts High School,General Academic,Secondary School,Common Core Algebra2,2016,All Students,All Students,58,66.3,21,36.2,37,63.8,3,5.2,37,63.8
999,02M408,Professional Performing Arts High School,General Academic,Secondary School,Common Core Algebra2,2017,All Students,All Students,60,69.1,17,28.3,43,71.7,5,8.3,43,71.7

In [12]:
df.shape

(1000, 18)

In [13]:
df.columns

Index(['school_dbn', 'school_name', 'school_type', 'school_level',
       'regents_exam', 'year', 'demographic_category', 'demographic_variable',
       'total_tested', 'mean_score', 'number_scoring_below_65',
       'percent_scoring_below_65', 'number_scoring_65_or_above',
       'percent_scoring_65_or_above', 'number_scoring_80_or_above',
       'percent_scoring_80_or_above', 'number_scoring_cr',
       'percent_scoring_cr'],
      dtype='object')

In [14]:
df.describe

<bound method NDFrame.describe of     school_dbn                               school_name       school_type  \
0       01M034            P.S. 034 Franklin D. Roosevelt  General Academic
1       01M034            P.S. 034 Franklin D. Roosevelt  General Academic
2       01M034            P.S. 034 Franklin D. Roosevelt  General Academic
3       01M140                    P.S. 140 Nathan Straus  General Academic
4       01M140                    P.S. 140 Nathan Straus  General Academic
..         ...                                       ...               ...
995     02M408  Professional Performing Arts High School  General Academic
996     02M408  Professional Performing Arts High School  General Academic
997     02M408  Professional Performing Arts High School  General Academic
998     02M408  Professional Performing Arts High School  General Academic
999     02M408  Professional Performing Arts High School  General Academic

         school_level          regents_exam  year demographic_category  \
0                 K-8   Common Core Algebra  2017         All Students
1                 K-8    Living Environment  2015         All Students
2                 K-8    Living Environment  2016         All Students
3                 K-8   Common Core Algebra  2016         All Students
4                 K-8   Common Core Algebra  2017         All Students
..                ...                   ...   ...                  ...
995  Secondary School   Common Core Algebra  2015         All Students
996  Secondary School   Common Core Algebra  2016         All Students
997  Secondary School   Common Core Algebra  2017         All Students
998  Secondary School  Common Core Algebra2  2016         All Students
999  Secondary School  Common Core Algebra2  2017         All Students

    demographic_variable  total_tested mean_score number_scoring_below_65  \
0           All Students             4          s                       s
1           All Students            16       77.9                       1
2           All Students             9       74.0                       1
3           All Students             3          s                       s
4           All Students             2          s                       s
..                   ...           ...        ...                     ...
995         All Students           113       67.9                      29
996         All Students           121       75.3                      13
997         All Students            96       80.8                       3
998         All Students            58       66.3                      21
999         All Students            60       69.1                      17

    percent_scoring_below_65 number_scoring_65_or_above  \
0                          s                          s
1                        6.3                         15
2                       11.1                          8
3                          s                          s
4                          s                          s
..                       ...                        ...
995                     25.7                         84
996                     10.7                        108
997                      3.1                         93
998                     36.2                         37
999                     28.3                         43

    percent_scoring_65_or_above number_scoring_80_or_above  \
0                             s                          s
1                          93.8                          7
2                          88.9                          2
3                             s                          s
4                             s                          s
..                          ...                        ...
995                        74.3                          8
996                        89.3                         44
997                        96.9                         68
998                        63.8                          3
999                        71.7                          5

    percent_scoring_80_or_above number_scoring_cr percent_scoring_cr
0                             s                na                 na
1                          43.8                na                 na
2                          22.2                na                 na
3                             s                na                 na
4                             s                na                 na
..                          ...               ...                ...
995                         7.1                51               45.1
996                        36.4                94               77.7
997                        70.8                89               92.7
998                         5.2                37               63.8
999                         8.3                43               71.7

[1000 rows x 18 columns]>

In [15]:
df.isnull().sum()

school_dbn                     0
school_name                    0
school_type                    0
school_level                   0
regents_exam                   0
year                           0
demographic_category           0
demographic_variable           0
total_tested                   0
mean_score                     0
number_scoring_below_65        0
percent_scoring_below_65       0
number_scoring_65_or_above     0
percent_scoring_65_or_above    0
number_scoring_80_or_above     0
percent_scoring_80_or_above    0
number_scoring_cr              0
percent_scoring_cr             0
dtype: int64

In [16]:
df.isnull().sum().sum()

0

In [17]:
pd.isna(df['number_scoring_cr'])

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Name: number_scoring_cr, Length: 1000, dtype: bool

In [18]:
pd.isna(df['number_scoring_cr']).count()

1000

In [22]:
df.isna(df['number_scoring_cr']).count().sort_values(ascending=False)

TypeError: ignored